server: 
  port: 9006
spring: 
  application:  
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.40.130 #指定服务名
      database: spitdb
  redis:
    host: 192.168.40.130
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
      prefer-ip-address: true